### ISSUE TITLE
transformer part numbers missing from schematic

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/mirny#13]
Also, let's make sure these are done consistently with other designs like phaser.
- where possible/appropriate use same transformer part numbers as other designs
- for external clock inputs try to do the layout such that we can use the transformer to provide galvanic isolation (not an option for microwave inputs)

**Comment by gkasprow** [comment]
what about the same transformers as in Phaser design?
![obraz](https://user-images.githubusercontent.com/4325054/94680315-d78bce80-0321-11eb-8a8c-c2402fd6ebfc.png)

**Comment by hartytp** [comment]
fine by me

**Comment by hartytp** [comment]
@gkasprow shouldn't the input ground be tied to the SMA ground, and only connected to the PCB ground through the 0R resistor though? That way we can use the transformers to provide galvanic isolation if desired (but let's not make that the default population option). IIRC that's what we're now typically doing elsewhere...

**Comment by gkasprow** [comment]
ah, yes, good point.
