### ISSUE TITLE
TPS62175DQC

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/mirny#16]
Why arent' we using the same PN as Urukul out of curiosity? Makes the design review easier if I'm just looking for diffs between the two designs...

**Comment by gkasprow** [comment]
it is already used in DIO boards. We can switch to the same one as in Urukul.
In Urukul it was used to generate 7V5 which was out of it spec that's why was replaced by TPS62148.
Here we generate 5V5 which is fine.

**Comment by hartytp** [comment]
@gkasprow I don't feel strongly about this (beyond a general preference for reusing components from other design where possible) so do what you think is best.

**Comment by gkasprow** [comment]
Let's go for Urukul one. It has higher current, mezzanines may need it.
