### ISSUE TITLE
Different supply for digital rails?

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/mirny#18]
Shouldn't the noisy PLL digital rails be run from a separate supply to the analog rails? E.g. run them directly from their own SMPSs.

**Comment by hartytp** [comment]
Maybe not needed if the digital interface is only used during configuration?

**Comment by gkasprow** [comment]
I'm a bit afraid of connecting it to the "digital" P3V3. I can replace the FB with an inductor that makes a low frequency filter.

**Comment by gkasprow** [comment]
![obraz](https://user-images.githubusercontent.com/4325054/94679323-351f1b80-0320-11eb-8d4f-c8e98f8eecbf.png)

**Comment by hartytp** [comment]
sure, whatever you think is best here...
