### ISSUE TITLE
power supply bug

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/mirny#2]
@jordens discovered [issue](https://github.com/sinara-hw/Urukul/issues/20) with the power supply in Urukul
The DC/DC converter has an output voltage higher than the specification says. We should look for another buck converter producing 7.5V
Another issue is bypass capacitor of LDO - with 100nF it oscillates.

**Comment by gkasprow** [comment]
@CannaCardo 
- [ ] C170, C175 must be 100pF. Replace with the component from libraries, do not edit parameters with value.

**Comment by CannaCardo** [comment]
fixed

**Comment by hartytp** [comment]
@CannaCardo should we close? Which release is this fixed in?

**Comment by CannaCardo** [comment]
It was fixed in v1.0rc4.

**Comment by gkasprow** [comment]
@CannaCardo are you currently working on new revision or only are closing old issues?

**Comment by CannaCardo** [comment]
Just closing, I'm working on the TDC atm.
