### ISSUE TITLE
RFoutB-

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/mirny#20]
why isn't this labelled AGNDrf2 and tied directly to GND1 as in the eval board?

**Comment by jordens** [comment]
I think this depends on the chip. The non-doubling are differential. Otherwise this is the Rf b return.

**Comment by hartytp** [comment]
That's what I assumed. AFAICT for the chip on Mirny right now this should be grounded as in the eval board. Maybe add shunt resistor to ground in parallel and DNP the cap?

**Comment by jordens** [comment]
I'd just test whether this works fine with the doubling variants and if not check whether making the R 0 is sufficient to enable AC return. If it works fine as now then no changes are needed.

**Comment by gkasprow** [comment]
I added 0R for ADF5356/5355 versions.
