### ISSUE TITLE
More flexible clock routing

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/mirny#23]
https://github.com/sinara-hw/mirny/issues/10#issuecomment-558618102

**Comment by gkasprow** [comment]
@hartytp @jordens would such wiring work for you?
![obraz](https://user-images.githubusercontent.com/4325054/94678020-20da1f00-031e-11eb-8c02-dc52da29f7d8.png)

**Comment by hartytp** [comment]
That arrangement allows one to select between the SMA and the VCXO/MMCX on a per-channel basis. For our use-cases, it would be more convenient to select between the MMCX and the SMA/VCXO on a per-channel basis, but the above is acceptable. @jordens preferences here?

@gkasprow based on our previous experience, I guess we expect quite a bit of cross-talk from the DNPd jumpers, do we?

**Comment by gkasprow** [comment]
we can use T-type jumpers, when unused, the central part is grounded.

**Comment by jordens** [comment]
Either is fine by me.

**Comment by jordens** [comment]
Default population being all channels clocked from IC13.

**Comment by gkasprow** [comment]
I added such a scheme. To avoid dangling nets, the segment is terminated on both sides. To improve isolation, unused net segments can be grounded. That should solve the issue with crosstalk.
![obraz](https://user-images.githubusercontent.com/4325054/94729840-97990b80-0362-11eb-935a-3ff2538d2320.png)

**Comment by gkasprow** [comment]
I also changed the assignment - now we select between MMCX and the SMA/VCXO.

**Comment by gkasprow** [comment]
The layout/routing of the clocking section
![obraz](https://user-images.githubusercontent.com/4325054/94735024-615f8a00-036a-11eb-8ec3-3d12816494d1.png)
