### ISSUE TITLE
Output crosstalk due to lacking isolation 

### ISSUE THREAD

**Issue by nkrackow** [sinara-hw/mirny#36]
The outputs of current Mirnies V1.1 suffer from significant crosstalk:
![PNG1](https://user-images.githubusercontent.com/17088194/208652565-3d9ec3f0-719e-4621-88f7-bebf6d5884a2.png)

Pushing on the PCB close to the front panel makes the crosstalk vary by more than 10 dB. 
The SMA shield is shorted to the front panel at DC. 

This implies that there is a problem with the front panel, probably the SMA pins making connection.
The same issue appears on other high frequency sinara modules: https://github.com/sinara-hw/Urukul/issues/68

@gkasprow @akaminska

**Comment by kaolpr** [comment]
I believe SMA shield is just shorted to FP in a defined assembly variants:
![image](https://user-images.githubusercontent.com/9166701/208694076-df9904cf-ee38-476e-9e71-2fe8ef8fca9d.png)
![image](https://user-images.githubusercontent.com/9166701/208694429-10310362-e929-4cfa-8754-dafe81faf72b.png)

**Comment by gkasprow** [comment]
yes, but the impedance of short-circuit may be non-negligible for 1GHz and above

**Comment by akaminska** [comment]
We will try to re-create and investigate the problem

**Comment by gkasprow** [comment]
To do this, we need more info about the setup. Preferably some photos depict how cables are placed.

**Comment by jordens** [comment]
@nkrackow sent a photo to @akaminska AFAIK

**Comment by gkasprow** [comment]
we plan new revision. What if we remove the assembly variant and connect the SMA connectors to solid GND?

**Comment by gkasprow** [comment]
added direct connection like in Urukul
