### ISSUE TITLE
Mirny v1.0 tests

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/mirny#7]
The Mirny is ready for tests
![2019-03-26 12 40 37](https://user-images.githubusercontent.com/4325054/54996177-dfe6a900-4fc8-11e9-859b-febb79cd240f.jpg)

**Comment by gkasprow** [comment]
- [ ] 0R installed instead of  C68 ABCD causing short of 5V power supply rail. 3V3 rail depends on this voltage. After removing shorts, all supples are fine.

**Comment by gkasprow** [comment]
CPLD is detected over JTAG

**Comment by gkasprow** [comment]
@CannaCardo it's time to connect ADI devkit and check if the synthesizers are working

**Comment by CannaCardo** [comment]
Ack, I should be in Warsaw on Thursday to test it.

**Comment by jordens** [comment]
Nice!

**Comment by gkasprow** [comment]
the CPLD cannot really set Hi-Z on CLK_SEL signal. the state is close to VCC.
With a touch of the probe, the Hi-Z appears and stays until power down. So it looks like additional init sequence would be needed that first sets low state and then Hi-Z.

**Comment by gkasprow** [comment]
Other than that Mirny works with ADI devkit as a controller.

**Comment by gkasprow** [comment]
We have some issue with 26kHz and its second and third harmonics. The carrier is 100MHz. Moreover, the analyzer sees the carrier shifted by 1kHz.
![11](https://user-images.githubusercontent.com/4325054/55564935-3787c180-56f9-11e9-92a9-4ce9feda2c32.PNG)

**Comment by gkasprow** [comment]
It looks like the noise source was outside. With analyzer and supply connected to same mains outlet the spectrum looks much better now.
![22](https://user-images.githubusercontent.com/4325054/55565135-90eff080-56f9-11e9-8349-b31f87d7f137.PNG)

**Comment by jordens** [comment]
It works on urukul. Just tristate it.

**Comment by jordens** [comment]
What are the conditions and settings there? With div32 and a 3.4 GHz vco the datasheet gets to -131dbc/hz at 10khz and 64 mhz pfd.

**Comment by gkasprow** [comment]
the SSA I have is not a really good one. It is a software option to the spectrum analyzer. It's good for quick debugging, not real measurements. 
With CMC added to the 12V power entry, the 26kHz peak disappeared.
We will make measurements with real SSA in a few days.

**Comment by gkasprow** [comment]
[Here](https://www.dropbox.com/s/8773l9b8eklw5bs/praca%20mgr%20277384_inz.pdf?dl=0) is the thesis of Krzysztof Belewicz

**Comment by jordens** [comment]
Well done. Congrats @CannaCardo

**Comment by jbqubit** [comment]
Thanks for the detailed writeup @CannaCardo! Great work!
